### ISSUE TITLE
Error thrown in areSameQuery

### ISSUE THREAD

**Issue by DustinWoods** [stevenvachon/urlobj#1]
This issue can easily be replicated by executing this:

       areSameQuery(
           { var1:'123' },
           { var1:'456' }
       );

When two queries are compared, and both contain same-length strings, they will wind up getting compared like arrays, instead of strings.

Should probably add this to the unit tests after fixing.

**Comment by stevenvachon** [comment]
Tip: magic github syntax is "closes #1" would've closed this issue automatically.

**Comment by DustinWoods** [comment]
Thanks for the tip!
