### ISSUE TITLE
wrong relation for urls that differ in filename

### ISSUE THREAD

**Issue by VasilyStrelyaev** [stevenvachon/urlobj#4]
```
urlobj.relation('http://fakeurl.com/dir1/dir2/filename.html',
                'http://fakeurl.com/dir1/dir2/differentFile.html')
```
This returns `UrlComponent.HASH`, which seems wrong.

**Comment by stevenvachon** [comment]
I'm not sure how that could be when this test passes: https://github.com/stevenvachon/urlobj/blob/master/test/6.dependent.urlRelation.js#L56-L58

**Comment by VasilyStrelyaev** [comment]
May be that's because of the `filenameIsIndex` check here
https://github.com/stevenvachon/urlobj/blob/c8262b8ed74d64917534f3809d516a49c3e798d8/lib/urlRelation.js#L65
which is `true` in the tested case but `false` in my case

**Comment by stevenvachon** [comment]
You're right. Thank you.
